
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_data_rest?serverTimezone=UTC
    password:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    rest:
      base-path: /api
